'use strict';
/*
 * build.js - assembles the single-file submission build.
 *
 * Reads src/template.html, inlines src/styles.css into a <style> block and
 * every src/*.js file (sorted by filename, which is the load order) into
 * labelled <script> blocks, then writes index.html at the repository root.
 *
 * Usage:
 *   node tools/build.js          release build (excludes src/99_debug.js)
 *   node tools/build.js --dev    development build (includes src/99_debug.js)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'index.html');
const DEBUG_FILE = '99_debug.js';

function build(dev) {
  const template = fs.readFileSync(path.join(SRC, 'template.html'), 'utf8');
  const css = fs.readFileSync(path.join(SRC, 'styles.css'), 'utf8').replace(/\s+$/, '');

  const files = fs.readdirSync(SRC)
    .filter(function (f) { return f.endsWith('.js'); })
    .sort()
    .filter(function (f) { return dev || f !== DEBUG_FILE; });

  const rule = '   ' + '='.repeat(66);
  const scripts = files.map(function (f) {
    const body = fs.readFileSync(path.join(SRC, f), 'utf8').replace(/\s+$/, '');
    return [
      '<script>',
      '/*',
      rule,
      '   ' + f,
      rule,
      '*/',
      body,
      '</script>'
    ].join('\n');
  }).join('\n\n');

  const manifest = [
    '<!--',
    '  Generated by tools/build.js. Edit the files in src/ and rebuild.',
    '  Build type: ' + (dev ? 'development' : 'release'),
    '  Source files, in load order:',
    files.map(function (f) { return '    ' + f; }).join('\n'),
    '-->'
  ].join('\n');

  let html = template;
  if (html.indexOf('<!-- BUILD:CSS -->') < 0 || html.indexOf('<!-- BUILD:JS -->') < 0) {
    throw new Error('template.html is missing a BUILD:CSS or BUILD:JS marker');
  }
  html = html.replace('<!-- BUILD:CSS -->', '<style>\n' + css + '\n</style>');
  html = html.replace('<!-- BUILD:JS -->', scripts);
  html = html.replace('<!-- BUILD:MANIFEST -->', manifest);

  fs.writeFileSync(OUT, html, 'utf8');
  return { files: files, bytes: Buffer.byteLength(html, 'utf8') };
}

module.exports = build;

if (require.main === module) {
  const dev = process.argv.indexOf('--dev') >= 0;
  const r = build(dev);
  const kb = (r.bytes / 1024).toFixed(1);
  console.log('built index.html (' + (dev ? 'dev' : 'release') + ') ' + kb + ' kB from ' + r.files.length + ' source files');
}
